title: Allison Skinner Web Design and Development
author: Allison Skinner
email: allisondskinner@gmail.com
description: > # this means to ignore newlines until "twitter_username:"
  Allison Skinner provides custom web design, web development and web maintenance for a variety of businesses in the Athens, Georgia and Atlanta, Georgia area.


# social links
twitter_username: skinner_design
github_username:  adskinner
rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com
collections:
   portfolio-examples:
     output: true

defaults:
  - scope:
      path: ""
      type: portfolio-examples
    values:
      layout: portfolio

show_excerpts: false # set to true to show excerpts on the homepage


# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%-m.%-d.%Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md



# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
